const data = {
  products: [
    {
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high-quality shirt',
    },
    {
      name: 'Adidas Slim Shirt',
      slug: 'Adidas-slim-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 30,
      description: 'high-quality product',
    },
    {
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 80,
      countInStock: 30,
      brand: 'Nike',
      rating: 4.3,
      numReviews: 40,
      description: 'high-quality product',
    },
    {
      name: 'Adidas Slim Pant',
      slug: 'adidas-slim-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 100,
      countInStock: 40,
      brand: 'Adidas',
      rating: 4.6,
      numReviews: 60,
      description: 'high-quality product',
    },
  ],
};

export default data;
